"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Image as KonvaImage, Layer, Line, Rect, Stage, Text, Transformer } from "react-konva";
import type Konva from "konva";
import type { CertificateElement, CertificateLayout } from "@/lib/certificate-layout";
import { TEMPLATE_FIELDS, replaceTemplateText } from "@/lib/template-fields";

type Asset = { id: string; url: string; width: number; height: number; mimeType: string };
type Props = { templateId: string };
const previewValues: Record<string, string> = {
  "member.fullName": "Maria da Silva", "member.course": "Engenharia Civil", "member.cpf": "000.000.000-00",
  "representative.fullName": "Representante da organização", "system.currentDate": new Intl.DateTimeFormat("pt-BR").format(new Date()),
};

function uid() { return crypto.randomUUID().replaceAll("-", "_"); }
function useCanvasImage(url?: string) {
  const [image, setImage] = useState<HTMLImageElement>();
  useEffect(() => { if (!url) return; const item = new Image(); item.crossOrigin = "anonymous"; item.onload = () => setImage(item); item.src = url; }, [url]);
  return image;
}

function AssetImage({ element, asset, selected, onSelect, onChange }: { element: Extract<CertificateElement, { type: "IMAGE" }>; asset?: Asset; selected: boolean; onSelect: () => void; onChange: (next: CertificateElement) => void }) {
  const image = useCanvasImage(asset?.url); const ref = useRef<Konva.Image>(null); const transformer = useRef<Konva.Transformer>(null);
  useEffect(() => { if (selected && ref.current && transformer.current) { transformer.current.nodes([ref.current]); transformer.current.getLayer()?.batchDraw(); } }, [selected]);
  return <><KonvaImage ref={ref} image={image} {...element} draggable onClick={onSelect} onTap={onSelect}
    onDragEnd={(event) => onChange({ ...element, x: event.target.x(), y: event.target.y() })}
    onTransformEnd={() => { const node = ref.current!; onChange({ ...element, x: node.x(), y: node.y(), width: Math.max(1, node.width() * node.scaleX()), height: Math.max(1, node.height() * node.scaleY()), rotation: node.rotation() }); node.scale({ x: 1, y: 1 }); }} />
    {selected && <Transformer ref={transformer} keepRatio={element.lockAspectRatio} rotateEnabled />}</>;
}

function EditableShape({ element, selected, preview, values, onSelect, onChange }: { element: Exclude<CertificateElement, { type: "IMAGE" }>; selected: boolean; preview: boolean; values: Record<string, string>; onSelect: () => void; onChange: (next: CertificateElement) => void }) {
  const textRef = useRef<Konva.Text>(null); const rectRef = useRef<Konva.Rect>(null); const lineRef = useRef<Konva.Line>(null); const transformer = useRef<Konva.Transformer>(null);
  const currentNode = useCallback(() => element.type === "TEXT" ? textRef.current : element.type === "RECTANGLE" ? rectRef.current : lineRef.current, [element.type]);
  useEffect(() => { const node = currentNode(); if (selected && node && transformer.current) { transformer.current.nodes([node]); transformer.current.getLayer()?.batchDraw(); } }, [selected, currentNode]);
  const shared = { x: element.x, y: element.y, width: element.width, height: element.height, rotation: element.rotation, opacity: element.opacity, draggable: !preview, onClick: onSelect, onTap: onSelect,
    onDragEnd: (event: Konva.KonvaEventObject<DragEvent>) => onChange({ ...element, x: event.target.x(), y: event.target.y() }),
    onTransformEnd: () => { const node = currentNode()!; onChange({ ...element, x: node.x(), y: node.y(), width: Math.max(1, node.width() * node.scaleX()), height: Math.max(1, node.height() * node.scaleY()), rotation: node.rotation() }); node.scale({ x: 1, y: 1 }); } };
  return <>{element.type === "TEXT" && <Text ref={textRef} {...shared} text={preview ? replaceTemplateText(element.text, values) : element.text} fontFamily={element.fontFamily === "TimesRoman" ? "Times New Roman" : element.fontFamily} fontSize={element.fontSize} fontStyle={`${element.fontWeight === "bold" ? "bold" : "normal"}${element.italic ? " italic" : ""}`} textDecoration={element.underline ? "underline" : ""} align={element.textAlign} fill={element.color} wrap="word" />}
    {element.type === "RECTANGLE" && <Rect ref={rectRef} {...shared} fill={element.fill} stroke={element.borderColor} strokeWidth={element.borderWidth} />}
    {element.type === "LINE" && <Line ref={lineRef} {...shared} points={[0, element.height / 2, element.width, element.height / 2]} stroke={element.color} strokeWidth={element.strokeWidth} />}
    {selected && !preview && <Transformer ref={transformer} rotateEnabled />}</>;
}

export default function CertificateEditor({ templateId }: Props) {
  const router = useRouter(); const [layout, setLayout] = useState<CertificateLayout>(); const [assets, setAssets] = useState<Asset[]>([]);
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [selectedId, setSelectedId] = useState<string>();
  const [preview, setPreview] = useState(false); const [message, setMessage] = useState("Carregando..."); const [saving, setSaving] = useState(false);
  const [values, setValues] = useState(previewValues); const history = useRef<CertificateLayout[]>([]); const future = useRef<CertificateLayout[]>([]); const copied = useRef<CertificateElement | undefined>(undefined);
  const selected = layout?.elements.find((element) => element.id === selectedId);
  useEffect(() => { fetch(`/api/certificate-templates/${templateId}`).then(async (response) => ({ response, data: await response.json() })).then(({ response, data }) => { if (!response.ok) throw new Error(data.message); setLayout(data.template.layoutJson); setName(data.template.name); setDescription(data.template.description || ""); setAssets(data.assets || []); setValues((current) => ({ ...current, "organization.name": data.preview.organizationName, "organization.shortName": data.preview.organizationShortName })); setMessage(""); }).catch((error) => setMessage(error.message || "Erro ao carregar.")); }, [templateId]);
  const changeLayout = useCallback((next: CertificateLayout) => { setLayout((current) => { if (current) { history.current.push(current); if (history.current.length > 30) history.current.shift(); } return next; }); future.current = []; }, []);
  const undo = useCallback(() => { setLayout((current) => { const previous = history.current.pop(); if (!current || !previous) return current; future.current.push(current); return previous; }); }, []);
  const redo = useCallback(() => { setLayout((current) => { const next = future.current.pop(); if (!current || !next) return current; history.current.push(current); return next; }); }, []);
  const update = (next: CertificateElement) => layout && changeLayout({ ...layout, elements: layout.elements.map((item) => item.id === next.id ? next : item) });
  const remove = useCallback(() => { if (!layout || !selectedId) return; changeLayout({ ...layout, elements: layout.elements.filter((item) => item.id !== selectedId) }); setSelectedId(undefined); }, [layout, selectedId, changeLayout]);
  const duplicate = useCallback(() => { if (!layout || !selected) return; const copy = { ...selected, id: uid(), x: selected.x + 20, y: selected.y + 20 } as CertificateElement; changeLayout({ ...layout, elements: [...layout.elements, copy] }); setSelectedId(copy.id); }, [layout, selected, changeLayout]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { const target = event.target as HTMLElement; if (["INPUT", "TEXTAREA", "SELECT"].includes(target.tagName)) return; const key = event.key.toLowerCase(); if (event.key === "Delete") remove(); if ((event.ctrlKey || event.metaKey) && key === "c" && selected) { event.preventDefault(); copied.current = selected; } if ((event.ctrlKey || event.metaKey) && key === "v" && copied.current && layout) { event.preventDefault(); const copy = { ...copied.current, id: uid(), x: copied.current.x + 20, y: copied.current.y + 20 } as CertificateElement; changeLayout({ ...layout, elements: [...layout.elements, copy] }); setSelectedId(copy.id); copied.current = copy; } if ((event.ctrlKey || event.metaKey) && key === "d") { event.preventDefault(); duplicate(); } if ((event.ctrlKey || event.metaKey) && key === "z") { event.preventDefault(); if (event.shiftKey) redo(); else undo(); } if ((event.ctrlKey || event.metaKey) && key === "y") { event.preventDefault(); redo(); } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [remove, duplicate, undo, redo, selected, layout, changeLayout]);
  const add = (type: CertificateElement["type"]) => { if (!layout) return; const base = { id: uid(), x: 120, y: 120, width: 400, height: 80, rotation: 0, opacity: 1 };
    const item: CertificateElement = type === "TEXT" ? { ...base, type, text: "Novo texto", fontFamily: "Helvetica", fontSize: 32, fontWeight: "normal", italic: false, underline: false, textAlign: "center", color: "#000000" } : type === "LINE" ? { ...base, type, height: 10, color: "#000000", strokeWidth: 2 } : { ...base, type: "RECTANGLE", height: 160, fill: "#FFFFFF", borderColor: "#000000", borderWidth: 2 };
    changeLayout({ ...layout, elements: [...layout.elements, item] }); setSelectedId(item.id); };
  async function uploadImage(background = false) { const input = document.createElement("input"); input.type = "file"; input.accept = "image/png,image/jpeg"; input.onchange = async () => { const file = input.files?.[0]; if (!file || !layout) return; const form = new FormData(); form.append("file", file); setMessage("Enviando imagem..."); const response = await fetch("/api/certificate-assets", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) return setMessage(data.message || "Falha no upload."); setAssets((current) => [...current, data.asset]); if (background) changeLayout({ ...layout, background: { type: "IMAGE", assetId: data.asset.id, fit: "cover", position: "center" } }); else { const item: CertificateElement = { id: uid(), type: "IMAGE", assetId: data.asset.id, x: 100, y: 100, width: 240, height: 160, rotation: 0, opacity: 1, lockAspectRatio: true }; changeLayout({ ...layout, elements: [...layout.elements, item] }); setSelectedId(item.id); } setMessage(""); }; input.click(); }
  async function save() { if (!layout) return; setSaving(true); setMessage(""); const response = await fetch(`/api/certificate-templates/${templateId}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description: description || null, layout }) }); const data = await response.json(); setSaving(false); setMessage(response.ok ? "Certificado salvo." : data.message || "Erro ao salvar."); }
  const scale = useMemo(() => layout ? Math.min(0.78, 760 / layout.page.width) : 1, [layout]);
  if (!layout) return <div className="rounded-lg border bg-white p-6 text-sm text-gray-600">{message}</div>;
  const background = layout.background;
  const backgroundAsset = background.type === "IMAGE" ? assets.find((asset) => asset.id === background.assetId) : undefined;
  return <div className="space-y-4"><div className="flex flex-wrap items-center gap-2 rounded-lg border bg-white p-3">
    <button className="rounded border px-3 py-2 text-sm" onClick={() => add("TEXT")}>Texto</button><button className="rounded border px-3 py-2 text-sm" onClick={() => uploadImage(false)}>Imagem</button><button className="rounded border px-3 py-2 text-sm" onClick={() => add("LINE")}>Linha</button><button className="rounded border px-3 py-2 text-sm" onClick={() => add("RECTANGLE")}>Retângulo</button><button className="rounded border px-3 py-2 text-sm" onClick={() => uploadImage(true)}>Fundo</button>
    <button className="rounded border px-3 py-2 text-sm" onClick={undo}>Desfazer</button><button className="rounded border px-3 py-2 text-sm" onClick={redo}>Refazer</button><button className="rounded border px-3 py-2 text-sm" onClick={() => setPreview((value) => !value)}>{preview ? "Editar" : "Preview"}</button>
    <button className="ml-auto rounded bg-[var(--admin-primary)] px-4 py-2 text-sm font-medium text-[var(--admin-on-primary)] disabled:opacity-50" disabled={saving} onClick={save}>{saving ? "Salvando..." : "Salvar"}</button><button className="rounded border px-3 py-2 text-sm" onClick={() => router.push(`/admin/documentos/modelos/certificados/${templateId}/gerar`)}>Gerar</button></div>
    {message && <p className="rounded border bg-white px-3 py-2 text-sm">{message}</p>}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="overflow-auto rounded-lg border bg-gray-100 p-4"><div className="mx-auto shadow-lg" style={{ width: layout.page.width * scale, height: layout.page.height * scale }}><Stage width={layout.page.width * scale} height={layout.page.height * scale} scaleX={scale} scaleY={scale} onMouseDown={(event) => { if (event.target === event.target.getStage()) setSelectedId(undefined); }}><Layer>
      {layout.background.type === "COLOR" ? <Rect width={layout.page.width} height={layout.page.height} fill={layout.background.color} /> : <BackgroundImage asset={backgroundAsset} width={layout.page.width} height={layout.page.height} />}
      {layout.elements.map((element) => element.type === "IMAGE" ? <AssetImage key={element.id} element={element} asset={assets.find((asset) => asset.id === element.assetId)} selected={!preview && selectedId === element.id} onSelect={() => !preview && setSelectedId(element.id)} onChange={update} /> : <EditableShape key={element.id} element={element} selected={!preview && selectedId === element.id} preview={preview} values={values} onSelect={() => !preview && setSelectedId(element.id)} onChange={update} />)}
    </Layer></Stage></div></div><aside className="space-y-4 rounded-lg border bg-white p-4"><label className="block text-sm">Nome<input className="mt-1 w-full rounded border px-3 py-2" value={name} maxLength={200} onChange={(e) => setName(e.target.value)} /></label>
      {!selected && <><label className="block text-sm">Cor do fundo<input type="color" className="ml-3" value={background.type === "COLOR" ? background.color : "#FFFFFF"} onChange={(e) => changeLayout({ ...layout, background: { type: "COLOR", color: e.target.value } })} /></label><label className="block text-sm">Imagem existente<select className="mt-1 w-full rounded border p-2" value={background.type === "IMAGE" ? background.assetId : ""} onChange={(e) => e.target.value && changeLayout({ ...layout, background: { type: "IMAGE", assetId: e.target.value, fit: "cover", position: "center" } })}><option value="">Selecione...</option>{assets.map((asset) => <option key={asset.id} value={asset.id}>Imagem {asset.id.slice(0, 8)}</option>)}</select></label>{background.type === "IMAGE" && <label className="block text-sm">Ajuste<select className="mt-1 w-full rounded border p-2" value={background.fit} onChange={(e) => changeLayout({ ...layout, background: { type: "IMAGE", assetId: background.assetId, position: background.position, fit: e.target.value as "cover" | "contain" } })}><option value="cover">Preencher</option><option value="contain">Conter</option></select></label>}<p className="text-xs text-gray-500">Selecione um elemento para editar suas propriedades.</p></>}
      {selected && <ElementProperties element={selected} onChange={update} onDelete={remove} onDuplicate={duplicate} onForward={() => changeLayout({ ...layout, elements: [...layout.elements.filter((e) => e.id !== selected.id), selected] })} onBackward={() => changeLayout({ ...layout, elements: [selected, ...layout.elements.filter((e) => e.id !== selected.id)] })} />}
    </aside></div></div>;
}

function BackgroundImage({ asset, width, height }: { asset?: Asset; width: number; height: number }) { const image = useCanvasImage(asset?.url); return <KonvaImage image={image} width={width} height={height} listening={false} />; }
function ElementProperties({ element, onChange, onDelete, onDuplicate, onForward, onBackward }: { element: CertificateElement; onChange: (e: CertificateElement) => void; onDelete: () => void; onDuplicate: () => void; onForward: () => void; onBackward: () => void }) {
  const number = (key: "x" | "y" | "width" | "height" | "rotation", value: number) => onChange({ ...element, [key]: value } as CertificateElement);
  return <div className="space-y-3"><p className="text-sm font-medium">{element.type}</p><div className="grid grid-cols-2 gap-2">{(["x", "y", "width", "height", "rotation"] as const).map((key) => <label key={key} className="text-xs">{key}<input type="number" className="mt-1 w-full rounded border px-2 py-1" value={Math.round(element[key])} onChange={(e) => number(key, Number(e.target.value))} /></label>)}</div>
    {element.type === "TEXT" && <><label className="block text-xs">Texto<textarea className="mt-1 h-28 w-full rounded border p-2" maxLength={4000} value={element.text} onChange={(e) => onChange({ ...element, text: e.target.value })} /></label><label className="block text-xs">Adicionar variável<select className="mt-1 w-full rounded border p-2" value="" onChange={(e) => e.target.value && onChange({ ...element, text: `${element.text}{{ ${e.target.value} }}` })}><option value="">Selecione...</option>{TEMPLATE_FIELDS.map((field) => <option key={field}>{field}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><label className="text-xs">Fonte<select className="mt-1 w-full rounded border p-1" value={element.fontFamily} onChange={(e) => onChange({ ...element, fontFamily: e.target.value as typeof element.fontFamily })}><option>Helvetica</option><option>TimesRoman</option><option>Courier</option></select></label><label className="text-xs">Tamanho<input type="number" min="6" max="200" className="mt-1 w-full rounded border p-1" value={element.fontSize} onChange={(e) => onChange({ ...element, fontSize: Number(e.target.value) })} /></label><label className="text-xs">Alinhamento<select className="mt-1 w-full rounded border p-1" value={element.textAlign} onChange={(e) => onChange({ ...element, textAlign: e.target.value as typeof element.textAlign })}><option value="left">Esquerda</option><option value="center">Centro</option><option value="right">Direita</option></select></label><label className="text-xs">Cor <input type="color" value={element.color} onChange={(e) => onChange({ ...element, color: e.target.value })} /></label></div><div className="flex gap-3 text-xs"><label><input type="checkbox" checked={element.fontWeight === "bold"} onChange={(e) => onChange({ ...element, fontWeight: e.target.checked ? "bold" : "normal" })} /> Negrito</label><label><input type="checkbox" checked={element.italic} onChange={(e) => onChange({ ...element, italic: e.target.checked })} /> Itálico</label><label><input type="checkbox" checked={element.underline} onChange={(e) => onChange({ ...element, underline: e.target.checked })} /> Sublinhado</label></div></>}
    {element.type === "LINE" && <><label className="text-xs">Cor <input type="color" value={element.color} onChange={(e) => onChange({ ...element, color: e.target.value })} /></label><label className="block text-xs">Espessura<input type="number" min="1" max="40" className="mt-1 w-full rounded border p-1" value={element.strokeWidth} onChange={(e) => onChange({ ...element, strokeWidth: Number(e.target.value) })} /></label></>}
    {element.type === "RECTANGLE" && <div className="grid grid-cols-2 gap-2"><label className="text-xs">Preenchimento<input type="color" value={element.fill} onChange={(e) => onChange({ ...element, fill: e.target.value })} /></label><label className="text-xs">Borda<input type="color" value={element.borderColor} onChange={(e) => onChange({ ...element, borderColor: e.target.value })} /></label><label className="text-xs">Espessura<input type="number" min="0" max="40" className="mt-1 w-full rounded border p-1" value={element.borderWidth} onChange={(e) => onChange({ ...element, borderWidth: Number(e.target.value) })} /></label></div>}
    <div className="grid grid-cols-2 gap-2 text-xs"><button className="rounded border p-2" onClick={onForward}>Frente</button><button className="rounded border p-2" onClick={onBackward}>Trás</button><button className="rounded border p-2" onClick={onDuplicate}>Duplicar</button><button className="rounded border border-red-300 p-2 text-red-700" onClick={onDelete}>Excluir</button></div></div>;
}
