"use client";
import { use, useEffect, useState } from "react";
type Member = { id: string; fullName: string };
export default function GenerateCertificatePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [members, setMembers] = useState<Member[]>([]); const [memberId, setMemberId] = useState(""); const [representativeId, setRepresentativeId] = useState(""); const [message, setMessage] = useState(""); const [url, setUrl] = useState("");
  useEffect(() => { fetch("/api/members").then((r) => r.json()).then((data) => setMembers(data.members || [])); }, []);
  async function generate(event: React.FormEvent) { event.preventDefault(); setMessage("Gerando PDF oficial..."); setUrl(""); const response = await fetch(`/api/certificate-templates/${id}/generate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ memberId, representativeId: representativeId || null }) }); const data = await response.json(); setMessage(response.ok ? "Certificado gerado e registrado." : data.message || "Erro ao gerar."); if (response.ok) setUrl(data.downloadUrl); }
  return <div className="max-w-xl"><h1 className="text-2xl font-semibold">Gerar certificado</h1><p className="mt-1 text-sm text-gray-600">O PDF será renderizado no servidor e armazenado de forma privada.</p><form onSubmit={generate} className="mt-6 space-y-4 rounded-lg border bg-white p-6"><label className="block text-sm">Membro<select required className="mt-1 w-full rounded border p-2" value={memberId} onChange={(e) => setMemberId(e.target.value)}><option value="">Selecione...</option>{members.map((member) => <option key={member.id} value={member.id}>{member.fullName}</option>)}</select></label><label className="block text-sm">Representante (opcional)<select className="mt-1 w-full rounded border p-2" value={representativeId} onChange={(e) => setRepresentativeId(e.target.value)}><option value="">Nenhum</option>{members.map((member) => <option key={member.id} value={member.id}>{member.fullName}</option>)}</select></label><button className="rounded bg-violet-700 px-4 py-2 text-sm font-medium text-white">Gerar PDF</button>{message && <p className="text-sm">{message}</p>}{url && <a className="inline-block font-medium text-violet-700" href={url} target="_blank" rel="noreferrer">Baixar PDF (link temporário)</a>}</form></div>;
}
