"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Template = { id: string; name: string; description: string | null; processingVersion: number; updatedAt: string };
export default function CertificateTemplatesPage() {
  const [items, setItems] = useState<Template[]>([]); const [message, setMessage] = useState("Carregando...");
  const load = () => fetch("/api/certificate-templates").then((r) => r.json()).then((data) => { if (!data.ok) throw new Error(data.message); setItems(data.templates); setMessage(""); }).catch((e) => setMessage(e.message));
  useEffect(() => { void load(); }, []);
  async function action(id: string, kind: "duplicate" | "delete") { const response = await fetch(`/api/certificate-templates/${id}${kind === "duplicate" ? "/duplicate" : ""}`, { method: kind === "duplicate" ? "POST" : "DELETE" }); const data = await response.json(); setMessage(response.ok ? (kind === "duplicate" ? "Certificado duplicado." : "Certificado excluído.") : data.message); if (response.ok) load(); }
  return <div className="max-w-6xl"><div className="mb-6 flex items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold">Certificados visuais</h1><p className="mt-1 text-sm text-gray-600">Crie certificados A4 e gere PDFs oficiais para membros.</p></div><Link href="/admin/documentos/modelos/certificados/novo" className="rounded bg-violet-700 px-4 py-2 text-sm font-medium text-white">+ Novo certificado visual</Link></div>
    {message && <p className="mb-4 rounded border bg-white p-3 text-sm">{message}</p>}<div className="overflow-hidden rounded-lg border bg-white">{!message && items.length === 0 ? <p className="p-8 text-center text-sm text-gray-500">Nenhum certificado visual criado.</p> : <table className="w-full text-left text-sm"><thead className="border-b bg-gray-50"><tr><th className="p-4">Nome</th><th className="p-4">Versão</th><th className="p-4">Ações</th></tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.id}><td className="p-4"><p className="font-medium">{item.name}</p><p className="text-xs text-gray-500">{item.description || "Sem descrição"}</p></td><td className="p-4">{item.processingVersion}</td><td className="p-4"><div className="flex gap-3"><Link className="font-medium text-violet-700" href={`/admin/documentos/modelos/certificados/${item.id}/editar`}>Editar</Link><button onClick={() => action(item.id, "duplicate")}>Duplicar</button><button className="text-red-600" onClick={() => confirm("Excluir este certificado? Os documentos já gerados manterão o snapshot histórico.") && action(item.id, "delete")}>Excluir</button></div></td></tr>)}</tbody></table>}</div></div>;
}
